# Jekyll configuration file for Vitrina
title: Vitrina
description: A general purpose Jekyll theme.
url: "https://joseaugustogoulart.me/vitrina"
lang: en-US
paginate: 5
paginate_path: /blog/:num
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/banner.png
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /blog/:title
      categories: blog

# Caution with the configurations below
exclude: [
  yarn.lock,
  Gemfile.lock,
  jekyll-theme-vitrina.gemspec,
  Gemfile, vendor, scripts,
  node_modules/bulma,
  node_modules/fork-awesome/*.md,
  node_modules/fork-awesome/*ss
]
