# Jekyll configuration file for Vitrina

# Title of the site
title: Vitrina
# Description of the site
description: A general purpose Jekyll theme.
# Site URL
url: "https://oagoulart.github.io/vitrina"
lang: en-US
paginate: 5
paginate_path: /blog/:num
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/banner.png
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /blog/:title
      categories: blog
collections:
  projects:
    output: false
  papers:
    output: false

# Caution with the configurations below
exclude: [
  yarn.lock,
  Gemfile.lock,
  jekyll-theme-vitrina.gemspec,
  Gemfile, vendor, scripts,
  node_modules/bulma,
  node_modules/fork-awesome/*.md,
  node_modules/fork-awesome/*ss
]
