title: Vitrina
description: A general purpose Jekyll theme.
lang: en-US
permalink: /:categories/:title

# Don't change the configurations below
exclude: [yarn.lock, Gemfile.lock, jekyll-theme-vitrina.gemspec, Gemfile, vendor, scripts, node_modules/bulma, node_modules/fork-awesome/*.md, node_modules/fork-awesome/*ss]
